name: 'Hello World'
description: 'Greet someone'

inputs:
  plan_dir:
    description: "Path to the location of the plan file"
    required: true


runs:
  using: "composite"
  steps:
    - name: Set Path
      shell: bash
      run: |
        echo "This is the path: ${{inputs.plan_dir}}"
        ls -al
      working-directory: ${{inputs.plan_dir}}

    - name: Archive code
      uses: actions/upload-artifacts@v3
      with:
        name: set1-plan
        path: set1/set1-dir.txt
