name: 'Apply'
description: 'Used to apply'

inputs:
  artifact_name:
    description: "Path to the location of the plan file"
    required: false


runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v2
      with:
        name: set1-plan

    - name: Set Path
      shell: bash
      run: |
        ls -al
